name: test C compilation
on: 
  push:
permissions: write-all
  
jobs:
   build:
        runs-on: ubuntu-latest
        container:
          image: ruby:2.7
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: compilation
              run: gcc -Wall -static -o hello hello.c
            - name: upload des binaires
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.job }}-${{ github.sha }}
                path: |
                  ./hello
