name: test C compilation
on: 
  workflow_dispatch:
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: compilation
              run: gcc -Wall -static -o hello hello.c
            - name: upload des binaires
              uses: actions/upload-artifact@v4
              with:
                name: hello_compil
                path: ./hello 
    exetest:
        runs-on: self-hosted
        container:
            image: alpine:latest
        needs: [build]
        steps:
            - name: dwnload des binaires
              uses: actions/download-artifact@v4
              with:
                name: hello_compil
            - name: lister les fichiers
              run: ls -la
            - name: exe test
              run: |
                  chmod +x hello
                  ./hello

