name: test C compilation
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: compilation
              run: gcc -Wall -o hello hello.c
            - name: upload des binaires
              uses: actions/upload-artifact@v3
              with:
                name: hello_compil
                path: ./hello 
    exetest:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: dwnload des binaires
              uses: actions/download-artifact@v4
              with:
                name: hello_compil
            - name: exe test
              run: ./hello

