name: test C compilation
on: 
  workflow_dispatch:
permissions:
  actions: write
  
jobs:
    lintc:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: lint
          run: gcc -fsyntax-only hello.c
    lintpy:
      runs-on: ubuntu-latest
      steps:
        - name: lint py
          run: echo lint
    build:
        runs-on: ubuntu-latest
        needs: lintc
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: compilation
              run: gcc -Wall -static -o hello hello.c
            - name: test
              run: |
                mkdir my_app
                echo test > my_app/test.txt
            - name: upload des binaires
              uses: actions/upload-artifact@v4
              with:
                name: hello_compil
                path: |
                  ./hello
                  my_app/test.txt
    exetest:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        needs: [build]
        steps:
            - name: dwnload des binaires
              uses: actions/download-artifact@v4
              with:
                name: hello_compil
            - name: lister les fichiers
              run: ls -la
            - name: exe test
              run: |
                  chmod +x hello
                  ./hello
    deploy_c:
        runs-on: ubuntu-latest
        needs: [exetest]
        steps:
            - name: deploy
              run: echo deploy
